# Generated by Django 3.1.1 on 2020-09-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminzone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notificationdate',
            field=models.CharField(max_length=30),
        ),
    ]
